---
title: MSSQLSERVER_8680 | Microsoft Docs
ms.custom: ''
ms.date: 04/04/2017
ms.prod: sql
ms.prod_service: database-engine
ms.component: errors-events
ms.reviewer: ''
ms.suite: sql
ms.technology: supportability
ms.tgt_pltfrm: ''
ms.topic: language-reference
helpviewer_keywords:
- 8680 (Database Engine error)
ms.assetid: 79f7270e-e4df-4f4e-bc78-2dcad6a9f140
caps.latest.revision: 13
author: MashaMSFT
ms.author: mathoma
manager: craigg
ms.openlocfilehash: d8a66dc7d04ec55d496b5c3809925ae2fa39b287
ms.sourcegitcommit: f1caaa156db2b16e817e0a3884394e7b30fb642f
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 05/04/2018
---
# <a name="mssqlserver8680"></a>MSSQLSERVER_8680
[!INCLUDE[appliesto-ss-xxxx-xxxx-xxx-md](../../includes/appliesto-ss-xxxx-xxxx-xxx-md.md)]
  
## <a name="details"></a>Detalhes  
  
|||  
|-|-|  
|Nome do produto|SQL Server|  
|ID do evento|8680|  
|Origem do evento|MSSQLSERVER|  
|Componente|SQLEngine|  
|Nome simbólico|REMOTE_ERR|  
|Texto da mensagem|Erro interno do processador de consultas: erro inesperado durante o processamento de uma fase de consulta remota.|  
  
## <a name="explanation"></a>Explicação  
Erro interno de processamento de consultas.  
  
## <a name="user-action"></a>Ação do usuário  
Contate o Suporte e Atendimento ao Cliente Microsoft (CSS) e forneça uma descrição do erro, dos rastreamentos ou dos despejos (se disponível).  
  
